# Generated by Django 5.0.6 on 2024-07-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0004_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
